# Generated by Django 5.2.7 on 2025-11-23 19:19

import notices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=notices.models.notice_upload_path)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
