# Generated by Django 5.2.8 on 2025-11-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('course', models.CharField(max_length=80)),
                ('branch', models.CharField(max_length=80)),
                ('semester', models.IntegerField(default=1)),
                ('section', models.CharField(default='A', max_length=5)),
                ('admission_no', models.CharField(max_length=50)),
                ('admission_year', models.CharField(max_length=10)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
