# Generated by Django 5.2.7 on 2025-11-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
    ]
